name: Upload dotnet package

on:
  release:
    types: [created]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x' # SDK Version to use.
          source-url: https://nuget.pkg.github.com/zahichemaly/index.json
        env:
          NUGET_AUTH_TOKEN: ${{secrets.NUGET_AUTH}}
      - run: dotnet build --configuration Release WebApp
      - name: Create the package
        run: dotnet pack --configuration Release WebApp
      - name: Publish the package to GPR
        run: dotnet nuget push WebApp/bin/Release/*.nupkg
